### PR TITLE
Optimized _packedLogsMalloc function

### PR DESCRIPTION
**Pull request by de33**
## Description

Optimized by:
- starting memory allocation directly at the current free memory pointer

- calculating the offset for log data immediately after storing the number of logs n

- adjusting the free memory pointer using mul(n, 0x20)

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge fmt`?
- [x] Ran `forge snapshot`?
- [x] Ran `forge test`?

### CODE REVIEW

**Comment by cygaar** [comment]
Can you run forge snapshot

**Comment by de33** [comment]
> Can you run forge snapshot

Done!

**Comment by Vectorized** [comment]
Don't merge. The offset by 2 words is absolutely necessary.

**Comment by Vectorized** [comment]
@de33 My bad, 2 words of memory is implicity allocated for `p`.

Made a new PR that includes this function and merged with your co-authorship.

Thanks!

**Pull request closed without merging**
